### ISSUE TITLE
Java Aufgabe CarryOn

### ISSUE THREAD

**Issue by Dennis-V1** [surfmuggle/Cubert#34]
das hier ist mein Code den ich bisher habe.  Der laeuft leider so nicht richtig:

import java.util.Scanner;

public class CarryOn 
{

    public static void main(String[] args) 
    {
        Scanner scanner = new Scanner(System.in);
        while(true) {
        System.out.println("Shall we carry on (enter yes,ye or y to continue and n to stop)?");
        String input = scanner.nextLine();
        if (input.equals("yes")  || (input.equals("ye") || (input.equals("y")) 
        {
            System.out.println("Shall we carry on?");
         } 
         else if (input.equals("n"))
         {
                System.out.println("stop");
         } // else
        } // while
    } // method
}

**Comment by Dennis-V1** [comment]
![Carry on aufgabe](https://user-images.githubusercontent.com/71431080/110789205-e5019900-826f-11eb-9e70-c8f348bc2b17.PNG)

**Comment by surfmuggle** [comment]
import java.util.Scanner;

public class CarryOn 
{

    public static void main(String[] args) 
    {
        Scanner scanner = new Scanner(System.in);
        while(true)
        {
        System.out.println("Shall we carry on (enter yes,ye or y to continue and n to stop)?");
        String input = scanner.nextLine();
        if ( input.equals("yes")  || input.equals("ye") || input.equals("y")) 
        {
            System.out.println("Shall we carry on?");
         } 
         else if (input.equals("n"))
         {
                System.out.println("stop");
         } // else
        } // while
    } // method
}

**Comment by surfmuggle** [comment]
This line has superfluous ( 

- wrong: `(input.equals("ye") ||  (input.equals("y")) `
- correct: `input.equals("ye") ||  input.equals("y")) `
