### ISSUE TITLE
HTML 1 - basic github page, html 5 tags, good markup, floating divs

### ISSUE THREAD

**Issue by surfmuggle** [surfmuggle/Cubert#5]
This is to 
- [x] Create a github-page see https://pages.github.com/
- [x] use some html 5 tags like article, ?section?, nav in a menaingfull way inside the html markup
- [x] create a basic website where you float some divs
- [x] [Archive a card](https://docs.github.com/articles/archiving-cards-on-a-project-board/) or archive all cards in a column

**Comment by surfmuggle** [comment]
Please use https://github.com/surfmuggle/Cubert/issues/10 as well

**Comment by PhiMo17** [comment]
I am pretty much done with my GitHub page. (phimo17.github.io)
I may work on some details on Monday, but except for the header section, I wouldn't know what to work on.
I'd appreciate some feedback either directly here in this issue thread or during a daily.

**Comment by PhiMo17** [comment]
After reading issue #16, I could learn some JS and apply it to my site.
