### ISSUE TITLE
 Aufgabe 4.2.1.1 Einstieg - soziales Netzwerk

### ISSUE THREAD

**Issue by nilay-benli** [surfmuggle/Cubert#50]
Hey Marcus, 
Irgendwie verstehe ich die Aufgabenstellung  hier nicht im allgemeinen wie wir das mit Python etc. lösen sollen.
Könnten wir uns diese Aufgabe Morgen gemeinsam angucken? 
https://www.inf-schule.de/information/datenbanksysteme/gbuch/relationaledb/einstieg_soznw

**Comment by surfmuggle** [comment]
Wie besprochen lassen wir den Pyhton Part aus.
